//
//  LTLAlbumReflashIcon.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/13.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//

@import UIKit;



@interface LTLAlbumReflashIcon : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLAlbumReflashIconResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLAlbumReflashIconResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLAlbumReflashIconResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLAlbumReflashIconResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLAlbumReflashIconResizingBehavior;

extern CGRect LTLAlbumReflashIconResizingBehaviorApply(LTLAlbumReflashIconResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawArtboard;
+(void) drawArtboardWithFrame:(CGRect)frame resizing:(LTLAlbumReflashIconResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfArtboard;
+(UIImage *) imageOfArtboardWithSize:(CGSize)size resizing:(LTLAlbumReflashIconResizingBehavior)resizing;


@end
