//
//  LTLabout.m
//  音乐播放器
//
//  Created by 李泰良 on 16/12/16.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;
#import "LTLabout.h"



@implementation LTLabout


#pragma mark - Canvas Drawings

//! Page 1

+(void) drawAbout
{
    [LTLabout drawAboutWithFrame:CGRectMake(0, 0, 160, 160) resizing:LTLaboutResizingBehaviorAspectFit];
}

+(void) drawAboutWithFrame:(CGRect)frame resizing:(LTLaboutResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLaboutResizingBehaviorApply(resizing, CGRectMake(0, 0, 160, 160), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 160, resizedFrame.size.height / 160);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! Rectangle
    UIBezierPath *rectangle = [UIBezierPath bezierPathWithRoundedRect:CGRectMake(0, 0, 138, 138) cornerRadius:26];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 11, 11);
    CGContextSaveGState(context);
    rectangle.lineWidth = 10;
    CGContextBeginPath(context);
    CGContextAddPath(context, rectangle.CGPath);
    CGContextEOClip(context);
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [rectangle stroke];
    CGContextRestoreGState(context);
    CGContextRestoreGState(context);
    
    //! Fill 1
    UIBezierPath *fill1 = [UIBezierPath bezierPath];
    [fill1 moveToPoint:CGPointMake(56.6, 67.68)];
    [fill1 addCurveToPoint:CGPointMake(54.73, 67.8) controlPoint1:CGPointMake(55.95, 67.71) controlPoint2:CGPointMake(55.33, 67.76)];
    [fill1 addCurveToPoint:CGPointMake(44.88, 65.37) controlPoint1:CGPointMake(50.03, 68.13) controlPoint2:CGPointMake(47.44, 68.31)];
    [fill1 addCurveToPoint:CGPointMake(43.06, 65.24) controlPoint1:CGPointMake(44.42, 64.83) controlPoint2:CGPointMake(43.6, 64.77)];
    [fill1 addCurveToPoint:CGPointMake(42.93, 67.06) controlPoint1:CGPointMake(42.52, 65.71) controlPoint2:CGPointMake(42.46, 66.52)];
    [fill1 addCurveToPoint:CGPointMake(51.25, 70.56) controlPoint1:CGPointMake(45.42, 69.93) controlPoint2:CGPointMake(48.11, 70.56)];
    [fill1 addCurveToPoint:CGPointMake(54.91, 70.38) controlPoint1:CGPointMake(52.41, 70.56) controlPoint2:CGPointMake(53.62, 70.47)];
    [fill1 addCurveToPoint:CGPointMake(56.75, 70.26) controlPoint1:CGPointMake(55.5, 70.34) controlPoint2:CGPointMake(56.11, 70.3)];
    [fill1 addCurveToPoint:CGPointMake(57.97, 68.89) controlPoint1:CGPointMake(57.46, 70.22) controlPoint2:CGPointMake(58.01, 69.6)];
    [fill1 addCurveToPoint:CGPointMake(56.6, 67.68) controlPoint1:CGPointMake(57.92, 68.18) controlPoint2:CGPointMake(57.29, 67.63)];
    [fill1 addLineToPoint:CGPointMake(56.6, 67.68)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(60.31, 67.49)];
    [fill1 addCurveToPoint:CGPointMake(59.02, 68.72) controlPoint1:CGPointMake(59.59, 67.49) controlPoint2:CGPointMake(59.02, 68.01)];
    [fill1 addCurveToPoint:CGPointMake(60.29, 69.89) controlPoint1:CGPointMake(59.02, 69.43) controlPoint2:CGPointMake(59.58, 69.88)];
    [fill1 addCurveToPoint:CGPointMake(60.69, 69.67) controlPoint1:CGPointMake(60.41, 69.91) controlPoint2:CGPointMake(60.54, 69.67)];
    [fill1 addLineToPoint:CGPointMake(60.71, 69.67)];
    [fill1 addCurveToPoint:CGPointMake(61.92, 69.07) controlPoint1:CGPointMake(61.26, 69.67) controlPoint2:CGPointMake(61.74, 69.56)];
    [fill1 addCurveToPoint:CGPointMake(62.04, 68.79) controlPoint1:CGPointMake(62, 68.91) controlPoint2:CGPointMake(62.04, 68.98)];
    [fill1 addCurveToPoint:CGPointMake(60.31, 67.49) controlPoint1:CGPointMake(62.01, 67.52) controlPoint2:CGPointMake(60.73, 67.49)];
    [fill1 addLineToPoint:CGPointMake(60.31, 67.49)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(80.78, 39.58)];
    [fill1 addCurveToPoint:CGPointMake(78.46, 43.34) controlPoint1:CGPointMake(80.57, 41.1) controlPoint2:CGPointMake(79.73, 42.47)];
    [fill1 addCurveToPoint:CGPointMake(77.24, 49.34) controlPoint1:CGPointMake(76.73, 44.52) controlPoint2:CGPointMake(76.11, 47.6)];
    [fill1 addCurveToPoint:CGPointMake(77.9, 52.21) controlPoint1:CGPointMake(77.8, 50.19) controlPoint2:CGPointMake(78.03, 51.21)];
    [fill1 addCurveToPoint:CGPointMake(76.2, 55.07) controlPoint1:CGPointMake(77.75, 53.37) controlPoint2:CGPointMake(77.14, 54.38)];
    [fill1 addCurveToPoint:CGPointMake(75.11, 60.83) controlPoint1:CGPointMake(74.38, 56.41) controlPoint2:CGPointMake(74.52, 59.54)];
    [fill1 addCurveToPoint:CGPointMake(75.35, 62.49) controlPoint1:CGPointMake(75.34, 61.34) controlPoint2:CGPointMake(75.42, 61.92)];
    [fill1 addCurveToPoint:CGPointMake(73.79, 64.76) controlPoint1:CGPointMake(75.22, 63.45) controlPoint2:CGPointMake(74.65, 64.28)];
    [fill1 addCurveToPoint:CGPointMake(72.12, 67.05) controlPoint1:CGPointMake(72.98, 65.22) controlPoint2:CGPointMake(72.39, 66.03)];
    [fill1 addCurveToPoint:CGPointMake(72.52, 70.34) controlPoint1:CGPointMake(71.82, 68.2) controlPoint2:CGPointMake(71.97, 69.43)];
    [fill1 addCurveToPoint:CGPointMake(72.69, 71.42) controlPoint1:CGPointMake(72.74, 70.69) controlPoint2:CGPointMake(72.73, 71.12)];
    [fill1 addCurveToPoint:CGPointMake(71.4, 72.83) controlPoint1:CGPointMake(72.6, 72.16) controlPoint2:CGPointMake(71.95, 72.67)];
    [fill1 addCurveToPoint:CGPointMake(70.85, 73.07) controlPoint1:CGPointMake(71.2, 72.89) controlPoint2:CGPointMake(71.02, 72.97)];
    [fill1 addCurveToPoint:CGPointMake(67.15, 73.46) controlPoint1:CGPointMake(70.17, 73.46) controlPoint2:CGPointMake(67.9, 73.46)];
    [fill1 addCurveToPoint:CGPointMake(64.36, 73.42) controlPoint1:CGPointMake(66.32, 73.46) controlPoint2:CGPointMake(65.4, 73.44)];
    [fill1 addCurveToPoint:CGPointMake(59.87, 73.37) controlPoint1:CGPointMake(63.03, 73.4) controlPoint2:CGPointMake(61.55, 73.37)];
    [fill1 addCurveToPoint:CGPointMake(53.89, 73.49) controlPoint1:CGPointMake(57.73, 73.37) controlPoint2:CGPointMake(55.8, 73.43)];
    [fill1 addCurveToPoint:CGPointMake(49.4, 73.6) controlPoint1:CGPointMake(52.27, 73.55) controlPoint2:CGPointMake(50.83, 73.6)];
    [fill1 addCurveToPoint:CGPointMake(38.81, 67.27) controlPoint1:CGPointMake(43.01, 73.6) controlPoint2:CGPointMake(40.1, 72.71)];
    [fill1 addLineToPoint:CGPointMake(38.81, 35.44)];
    [fill1 addLineToPoint:CGPointMake(39.01, 34.65)];
    [fill1 addCurveToPoint:CGPointMake(38.98, 34.34) controlPoint1:CGPointMake(39.05, 34.55) controlPoint2:CGPointMake(38.94, 34.44)];
    [fill1 addCurveToPoint:CGPointMake(44.68, 24.58) controlPoint1:CGPointMake(39.48, 32.65) controlPoint2:CGPointMake(42.36, 28.17)];
    [fill1 addCurveToPoint:CGPointMake(50.6, 14.47) controlPoint1:CGPointMake(47.25, 20.58) controlPoint2:CGPointMake(49.67, 16.81)];
    [fill1 addCurveToPoint:CGPointMake(52.16, 5.25) controlPoint1:CGPointMake(51.89, 11.19) controlPoint2:CGPointMake(52.15, 7.47)];
    [fill1 addCurveToPoint:CGPointMake(54.49, 5.64) controlPoint1:CGPointMake(52.92, 5.1) controlPoint2:CGPointMake(53.81, 5.19)];
    [fill1 addCurveToPoint:CGPointMake(59.05, 14.67) controlPoint1:CGPointMake(57.09, 7.36) controlPoint2:CGPointMake(59.58, 9.48)];
    [fill1 addCurveToPoint:CGPointMake(57.21, 20.03) controlPoint1:CGPointMake(58.88, 16.28) controlPoint2:CGPointMake(58.07, 18.1)];
    [fill1 addCurveToPoint:CGPointMake(55.33, 24.94) controlPoint1:CGPointMake(56.51, 21.6) controlPoint2:CGPointMake(55.78, 23.23)];
    [fill1 addCurveToPoint:CGPointMake(55.08, 27.87) controlPoint1:CGPointMake(55.09, 25.84) controlPoint2:CGPointMake(55.09, 26.83)];
    [fill1 addCurveToPoint:CGPointMake(55, 29.91) controlPoint1:CGPointMake(55.07, 28.56) controlPoint2:CGPointMake(55.07, 29.26)];
    [fill1 addCurveToPoint:CGPointMake(55.57, 31.84) controlPoint1:CGPointMake(54.92, 30.61) controlPoint2:CGPointMake(55.12, 31.3)];
    [fill1 addCurveToPoint:CGPointMake(57.34, 32.78) controlPoint1:CGPointMake(56.01, 32.38) controlPoint2:CGPointMake(56.65, 32.72)];
    [fill1 addLineToPoint:CGPointMake(58.13, 32.85)];
    [fill1 addCurveToPoint:CGPointMake(68.47, 33.47) controlPoint1:CGPointMake(61.59, 33.15) controlPoint2:CGPointMake(65.18, 33.47)];
    [fill1 addCurveToPoint:CGPointMake(72.5, 33.45) controlPoint1:CGPointMake(70.1, 33.47) controlPoint2:CGPointMake(71.43, 33.46)];
    [fill1 addCurveToPoint:CGPointMake(75.24, 33.45) controlPoint1:CGPointMake(73.74, 33.43) controlPoint2:CGPointMake(74.64, 33.42)];
    [fill1 addCurveToPoint:CGPointMake(75.43, 33.45) controlPoint1:CGPointMake(75.28, 33.45) controlPoint2:CGPointMake(75.4, 33.45)];
    [fill1 addCurveToPoint:CGPointMake(76.12, 33.49) controlPoint1:CGPointMake(75.65, 33.45) controlPoint2:CGPointMake(75.88, 33.46)];
    [fill1 addCurveToPoint:CGPointMake(79.71, 35.57) controlPoint1:CGPointMake(77.55, 33.68) controlPoint2:CGPointMake(78.83, 34.42)];
    [fill1 addCurveToPoint:CGPointMake(80.78, 39.58) controlPoint1:CGPointMake(80.59, 36.72) controlPoint2:CGPointMake(80.97, 38.14)];
    [fill1 addLineToPoint:CGPointMake(80.78, 39.58)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(85.91, 40.26)];
    [fill1 addCurveToPoint:CGPointMake(83.82, 32.42) controlPoint1:CGPointMake(86.28, 37.46) controlPoint2:CGPointMake(85.54, 34.67)];
    [fill1 addCurveToPoint:CGPointMake(76.8, 28.36) controlPoint1:CGPointMake(82.1, 30.18) controlPoint2:CGPointMake(79.61, 28.73)];
    [fill1 addCurveToPoint:CGPointMake(75.44, 28.28) controlPoint1:CGPointMake(76.38, 28.3) controlPoint2:CGPointMake(75.92, 28.29)];
    [fill1 addCurveToPoint:CGPointMake(72.45, 28.27) controlPoint1:CGPointMake(74.77, 28.25) controlPoint2:CGPointMake(73.82, 28.26)];
    [fill1 addCurveToPoint:CGPointMake(68.47, 28.3) controlPoint1:CGPointMake(71.39, 28.28) controlPoint2:CGPointMake(70.08, 28.3)];
    [fill1 addCurveToPoint:CGPointMake(60.25, 27.84) controlPoint1:CGPointMake(65.91, 28.3) controlPoint2:CGPointMake(63.08, 28.08)];
    [fill1 addCurveToPoint:CGPointMake(60.34, 26.26) controlPoint1:CGPointMake(60.26, 27.24) controlPoint2:CGPointMake(60.27, 26.52)];
    [fill1 addCurveToPoint:CGPointMake(61.94, 22.13) controlPoint1:CGPointMake(60.68, 24.96) controlPoint2:CGPointMake(61.29, 23.59)];
    [fill1 addCurveToPoint:CGPointMake(64.19, 15.19) controlPoint1:CGPointMake(62.93, 19.92) controlPoint2:CGPointMake(63.95, 17.63)];
    [fill1 addCurveToPoint:CGPointMake(57.36, 1.33) controlPoint1:CGPointMake(64.99, 7.46) controlPoint2:CGPointMake(60.96, 3.72)];
    [fill1 addCurveToPoint:CGPointMake(52.92, 0) controlPoint1:CGPointMake(56.03, 0.45) controlPoint2:CGPointMake(54.54, 0)];
    [fill1 addCurveToPoint:CGPointMake(48.2, 1.27) controlPoint1:CGPointMake(50.38, 0) controlPoint2:CGPointMake(48.42, 1.14)];
    [fill1 addCurveToPoint:CGPointMake(46.96, 3.68) controlPoint1:CGPointMake(47.36, 1.77) controlPoint2:CGPointMake(46.89, 2.7)];
    [fill1 addCurveToPoint:CGPointMake(45.81, 12.56) controlPoint1:CGPointMake(47.06, 5.07) controlPoint2:CGPointMake(47.07, 9.37)];
    [fill1 addCurveToPoint:CGPointMake(40.36, 21.78) controlPoint1:CGPointMake(45.07, 14.44) controlPoint2:CGPointMake(42.68, 18.17)];
    [fill1 addCurveToPoint:CGPointMake(34.15, 32.69) controlPoint1:CGPointMake(36.97, 27.05) controlPoint2:CGPointMake(34.87, 30.45)];
    [fill1 addLineToPoint:CGPointMake(33.71, 33.84)];
    [fill1 addCurveToPoint:CGPointMake(33.63, 34.89) controlPoint1:CGPointMake(33.56, 34.17) controlPoint2:CGPointMake(33.63, 34.53)];
    [fill1 addLineToPoint:CGPointMake(33.63, 67.59)];
    [fill1 addCurveToPoint:CGPointMake(33.56, 68.2) controlPoint1:CGPointMake(33.63, 67.8) controlPoint2:CGPointMake(33.51, 68)];
    [fill1 addCurveToPoint:CGPointMake(49.25, 78.77) controlPoint1:CGPointMake(35.9, 77.95) controlPoint2:CGPointMake(42.82, 78.77)];
    [fill1 addCurveToPoint:CGPointMake(53.98, 78.67) controlPoint1:CGPointMake(50.73, 78.77) controlPoint2:CGPointMake(52.31, 78.72)];
    [fill1 addCurveToPoint:CGPointMake(59.83, 78.54) controlPoint1:CGPointMake(55.85, 78.61) controlPoint2:CGPointMake(57.78, 78.54)];
    [fill1 addCurveToPoint:CGPointMake(64.25, 78.59) controlPoint1:CGPointMake(61.48, 78.54) controlPoint2:CGPointMake(62.95, 78.57)];
    [fill1 addCurveToPoint:CGPointMake(67.14, 78.63) controlPoint1:CGPointMake(65.32, 78.61) controlPoint2:CGPointMake(66.28, 78.63)];
    [fill1 addCurveToPoint:CGPointMake(73.14, 77.7) controlPoint1:CGPointMake(69.7, 78.63) controlPoint2:CGPointMake(71.62, 78.47)];
    [fill1 addCurveToPoint:CGPointMake(77.82, 72.11) controlPoint1:CGPointMake(75.65, 76.85) controlPoint2:CGPointMake(77.48, 74.68)];
    [fill1 addCurveToPoint:CGPointMake(77.4, 68.55) controlPoint1:CGPointMake(77.99, 70.85) controlPoint2:CGPointMake(77.84, 69.64)];
    [fill1 addCurveToPoint:CGPointMake(80.48, 63.17) controlPoint1:CGPointMake(79.07, 67.23) controlPoint2:CGPointMake(80.19, 65.3)];
    [fill1 addCurveToPoint:CGPointMake(79.89, 58.84) controlPoint1:CGPointMake(80.67, 61.69) controlPoint2:CGPointMake(80.47, 60.2)];
    [fill1 addCurveToPoint:CGPointMake(79.88, 58.74) controlPoint1:CGPointMake(79.89, 58.81) controlPoint2:CGPointMake(79.88, 58.78)];
    [fill1 addCurveToPoint:CGPointMake(83.03, 52.9) controlPoint1:CGPointMake(81.62, 57.24) controlPoint2:CGPointMake(82.72, 55.19)];
    [fill1 addCurveToPoint:CGPointMake(81.97, 47.17) controlPoint1:CGPointMake(83.29, 50.92) controlPoint2:CGPointMake(82.92, 48.91)];
    [fill1 addCurveToPoint:CGPointMake(85.91, 40.26) controlPoint1:CGPointMake(84.12, 45.47) controlPoint2:CGPointMake(85.54, 42.99)];
    [fill1 addLineToPoint:CGPointMake(85.91, 40.26)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(14.55, 64.5)];
    [fill1 addLineToPoint:CGPointMake(13.91, 64.5)];
    [fill1 addCurveToPoint:CGPointMake(11.64, 66.76) controlPoint1:CGPointMake(12.66, 64.5) controlPoint2:CGPointMake(11.64, 65.51)];
    [fill1 addLineToPoint:CGPointMake(11.64, 67.41)];
    [fill1 addCurveToPoint:CGPointMake(13.91, 69.67) controlPoint1:CGPointMake(11.64, 68.66) controlPoint2:CGPointMake(12.66, 69.67)];
    [fill1 addLineToPoint:CGPointMake(14.55, 69.67)];
    [fill1 addCurveToPoint:CGPointMake(16.82, 67.41) controlPoint1:CGPointMake(15.8, 69.67) controlPoint2:CGPointMake(16.82, 68.66)];
    [fill1 addLineToPoint:CGPointMake(16.82, 66.76)];
    [fill1 addCurveToPoint:CGPointMake(14.55, 64.5) controlPoint1:CGPointMake(16.82, 65.51) controlPoint2:CGPointMake(15.8, 64.5)];
    [fill1 addLineToPoint:CGPointMake(14.55, 64.5)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(24.58, 69.76)];
    [fill1 addCurveToPoint:CGPointMake(20.79, 73.55) controlPoint1:CGPointMake(24.58, 71.85) controlPoint2:CGPointMake(22.88, 73.55)];
    [fill1 addLineToPoint:CGPointMake(8.97, 73.55)];
    [fill1 addCurveToPoint:CGPointMake(5.17, 69.76) controlPoint1:CGPointMake(6.87, 73.55) controlPoint2:CGPointMake(5.17, 71.85)];
    [fill1 addLineToPoint:CGPointMake(5.17, 41.12)];
    [fill1 addCurveToPoint:CGPointMake(8.97, 37.33) controlPoint1:CGPointMake(5.17, 39.03) controlPoint2:CGPointMake(6.87, 37.33)];
    [fill1 addLineToPoint:CGPointMake(20.79, 37.33)];
    [fill1 addCurveToPoint:CGPointMake(24.58, 41.12) controlPoint1:CGPointMake(22.88, 37.33) controlPoint2:CGPointMake(24.58, 39.03)];
    [fill1 addLineToPoint:CGPointMake(24.58, 69.76)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(20.79, 32.16)];
    [fill1 addLineToPoint:CGPointMake(8.97, 32.16)];
    [fill1 addCurveToPoint:CGPointMake(0, 41.12) controlPoint1:CGPointMake(4.01, 32.16) controlPoint2:CGPointMake(0, 36.17)];
    [fill1 addLineToPoint:CGPointMake(0, 69.76)];
    [fill1 addCurveToPoint:CGPointMake(8.97, 78.73) controlPoint1:CGPointMake(0, 74.71) controlPoint2:CGPointMake(4.01, 78.73)];
    [fill1 addLineToPoint:CGPointMake(20.79, 78.73)];
    [fill1 addCurveToPoint:CGPointMake(29.75, 69.76) controlPoint1:CGPointMake(25.74, 78.73) controlPoint2:CGPointMake(29.75, 74.71)];
    [fill1 addLineToPoint:CGPointMake(29.75, 41.12)];
    [fill1 addCurveToPoint:CGPointMake(20.79, 32.16) controlPoint1:CGPointMake(29.75, 36.17) controlPoint2:CGPointMake(25.74, 32.16)];
    [fill1 addLineToPoint:CGPointMake(20.79, 32.16)];
    [fill1 closePath];
    [fill1 moveToPoint:CGPointMake(20.79, 32.16)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 38, 40);
    fill1.usesEvenOddFillRule = YES;
    [[LTLThemeManager sharedManager].themeColor setFill];
    [fill1 fill];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}


#pragma mark - Canvas Images

//! Page 1

+(UIImage *) imageOfAbout
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(160, 160), NO, 0);
    [LTLabout drawAbout];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfAboutWithSize:(CGSize)size resizing:(LTLaboutResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLabout drawAboutWithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}


#pragma mark - Resizing Behavior

CGRect LTLaboutResizingBehaviorApply(LTLaboutResizingBehavior behavior, CGRect rect, CGRect target)
{
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero))
    {
        return rect;
    }
    
    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);
    
    switch (behavior)
    {
        case LTLaboutResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case LTLaboutResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case LTLaboutResizingBehaviorStretch:
            break;
        
        case LTLaboutResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }
    
    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}


@end
