//
//  LTLabout.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/16.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLabout : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLaboutResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLaboutResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLaboutResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLaboutResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLaboutResizingBehavior;

extern CGRect LTLaboutResizingBehaviorApply(LTLaboutResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawAbout;
+(void) drawAboutWithFrame:(CGRect)frame resizing:(LTLaboutResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfAbout;
+(UIImage *) imageOfAboutWithSize:(CGSize)size resizing:(LTLaboutResizingBehavior)resizing;


@end
