//
//  LTLButtonBorder.h
//  音乐播放器
//
//  Created by 李泰良 on 16/11/25.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLButtonBorder : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLButtonBorderResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLButtonBorderResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLButtonBorderResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLButtonBorderResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLButtonBorderResizingBehavior;

extern CGRect LTLButtonBorderResizingBehaviorApply(LTLButtonBorderResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawArtboard;
+(void) drawArtboardWithFrame:(CGRect)frame resizing:(LTLButtonBorderResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfArtboard;
+(UIImage *) imageOfArtboardWithSize:(CGSize)size resizing:(LTLButtonBorderResizingBehavior)resizing;


@end
