//
//  LTLcontact.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/16.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLcontact : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLcontactResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLcontactResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLcontactResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLcontactResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLcontactResizingBehavior;

extern CGRect LTLcontactResizingBehaviorApply(LTLcontactResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawContact;
+(void) drawContactWithFrame:(CGRect)frame resizing:(LTLcontactResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfContact;
+(UIImage *) imageOfContactWithSize:(CGSize)size resizing:(LTLcontactResizingBehavior)resizing;


@end
