//
//  LTLDownloadIcon.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/13.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLDownloadIcon : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLDownloadIconResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLDownloadIconResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLDownloadIconResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLDownloadIconResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLDownloadIconResizingBehavior;

extern CGRect LTLDownloadIconResizingBehaviorApply(LTLDownloadIconResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawDownload;
+(void) drawDownloadWithFrame:(CGRect)frame resizing:(LTLDownloadIconResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfDownload;
+(UIImage *) imageOfDownloadWithSize:(CGSize)size resizing:(LTLDownloadIconResizingBehavior)resizing;


@end
