//
//  LTLHeadIcon.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/13.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLHeadIcon : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLHeadIconResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLHeadIconResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLHeadIconResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLHeadIconResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLHeadIconResizingBehavior;

extern CGRect LTLHeadIconResizingBehaviorApply(LTLHeadIconResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawMore;
+(void) drawMoreWithFrame:(CGRect)frame resizing:(LTLHeadIconResizingBehavior)resizing;
+(void) drawPlay;
+(void) drawPlayWithFrame:(CGRect)frame resizing:(LTLHeadIconResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfMore;
+(UIImage *) imageOfMoreWithSize:(CGSize)size resizing:(LTLHeadIconResizingBehavior)resizing;
+(UIImage *) imageOfPlay;
+(UIImage *) imageOfPlayWithSize:(CGSize)size resizing:(LTLHeadIconResizingBehavior)resizing;


@end
