//
//  LTLlikeList.m
//  音乐播放器
//
//  Created by 李泰良 on 16/12/16.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;
#import "LTLlikeList.h"



@implementation LTLlikeList


#pragma mark - Canvas Drawings

//! Page 1

+(void) drawLikeList
{
    [LTLlikeList drawLikeListWithFrame:CGRectMake(0, 0, 160, 160) resizing:LTLlikeListResizingBehaviorAspectFit];
}

+(void) drawLikeListWithFrame:(CGRect)frame resizing:(LTLlikeListResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLlikeListResizingBehaviorApply(resizing, CGRectMake(0, 0, 160, 160), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 160, resizedFrame.size.height / 160);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! Rectangle
    UIBezierPath *rectangle = [UIBezierPath bezierPathWithRoundedRect:CGRectMake(0, 0, 138, 138) cornerRadius:26];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 11, 11);
    CGContextSaveGState(context);
    rectangle.lineWidth = 10;
    CGContextBeginPath(context);
    CGContextAddPath(context, rectangle.CGPath);
    CGContextEOClip(context);
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [rectangle stroke];
    CGContextRestoreGState(context);
    CGContextRestoreGState(context);
    
    //! Fill 1
    UIBezierPath *fill1 = [UIBezierPath bezierPath];
    [fill1 moveToPoint:CGPointMake(40.99, 15.55)];
    [fill1 addCurveToPoint:CGPointMake(38.61, 15.96) controlPoint1:CGPointMake(40.22, 15.01) controlPoint2:CGPointMake(39.16, 15.19)];
    [fill1 addCurveToPoint:CGPointMake(39.02, 18.34) controlPoint1:CGPointMake(38.07, 16.73) controlPoint2:CGPointMake(38.25, 17.8)];
    [fill1 addCurveToPoint:CGPointMake(40.88, 19.91) controlPoint1:CGPointMake(39.68, 18.81) controlPoint2:CGPointMake(40.3, 19.33)];
    [fill1 addCurveToPoint:CGPointMake(42.08, 20.41) controlPoint1:CGPointMake(41.21, 20.24) controlPoint2:CGPointMake(41.65, 20.41)];
    [fill1 addCurveToPoint:CGPointMake(43.29, 19.91) controlPoint1:CGPointMake(42.52, 20.41) controlPoint2:CGPointMake(42.96, 20.24)];
    [fill1 addCurveToPoint:CGPointMake(43.29, 17.49) controlPoint1:CGPointMake(43.96, 19.24) controlPoint2:CGPointMake(43.96, 18.16)];
    [fill1 addCurveToPoint:CGPointMake(40.99, 15.55) controlPoint1:CGPointMake(42.58, 16.78) controlPoint2:CGPointMake(41.81, 16.13)];
    [fill1 moveToPoint:CGPointMake(34.81, 12.77)];
    [fill1 addCurveToPoint:CGPointMake(18.26, 17.49) controlPoint1:CGPointMake(28.81, 11.37) controlPoint2:CGPointMake(22.62, 13.13)];
    [fill1 addLineToPoint:CGPointMake(17.78, 17.97)];
    [fill1 addCurveToPoint:CGPointMake(13.23, 25.78) controlPoint1:CGPointMake(15.61, 20.14) controlPoint2:CGPointMake(14.04, 22.84)];
    [fill1 addCurveToPoint:CGPointMake(14.42, 27.88) controlPoint1:CGPointMake(12.98, 26.69) controlPoint2:CGPointMake(13.51, 27.63)];
    [fill1 addCurveToPoint:CGPointMake(14.88, 27.94) controlPoint1:CGPointMake(14.57, 27.92) controlPoint2:CGPointMake(14.73, 27.94)];
    [fill1 addCurveToPoint:CGPointMake(16.52, 26.68) controlPoint1:CGPointMake(15.63, 27.94) controlPoint2:CGPointMake(16.31, 27.44)];
    [fill1 addCurveToPoint:CGPointMake(20.2, 20.39) controlPoint1:CGPointMake(17.17, 24.32) controlPoint2:CGPointMake(18.44, 22.14)];
    [fill1 addLineToPoint:CGPointMake(20.68, 19.91)];
    [fill1 addCurveToPoint:CGPointMake(34.04, 16.1) controlPoint1:CGPointMake(24.19, 16.39) controlPoint2:CGPointMake(29.18, 14.97)];
    [fill1 addCurveToPoint:CGPointMake(36.09, 14.82) controlPoint1:CGPointMake(34.95, 16.31) controlPoint2:CGPointMake(35.87, 15.74)];
    [fill1 addCurveToPoint:CGPointMake(34.81, 12.77) controlPoint1:CGPointMake(36.3, 13.9) controlPoint2:CGPointMake(35.73, 12.98)];
    [fill1 moveToPoint:CGPointMake(93.7, 45.67)];
    [fill1 addCurveToPoint:CGPointMake(93.48, 45.92) controlPoint1:CGPointMake(93.62, 45.75) controlPoint2:CGPointMake(93.55, 45.84)];
    [fill1 addCurveToPoint:CGPointMake(57.33, 88.87) controlPoint1:CGPointMake(82.68, 59.07) controlPoint2:CGPointMake(61.23, 84.96)];
    [fill1 addCurveToPoint:CGPointMake(53.65, 91.17) controlPoint1:CGPointMake(56.28, 89.92) controlPoint2:CGPointMake(54.79, 91.17)];
    [fill1 addCurveToPoint:CGPointMake(49.98, 88.87) controlPoint1:CGPointMake(52.74, 91.16) controlPoint2:CGPointMake(51.51, 90.39)];
    [fill1 addCurveToPoint:CGPointMake(13.6, 45.91) controlPoint1:CGPointMake(46.61, 85.49) controlPoint2:CGPointMake(24.71, 59.29)];
    [fill1 addCurveToPoint:CGPointMake(13.39, 45.67) controlPoint1:CGPointMake(13.53, 45.83) controlPoint2:CGPointMake(13.46, 45.75)];
    [fill1 addCurveToPoint:CGPointMake(6.83, 29.92) controlPoint1:CGPointMake(9.16, 41.45) controlPoint2:CGPointMake(6.83, 35.85)];
    [fill1 addCurveToPoint:CGPointMake(13.39, 14.16) controlPoint1:CGPointMake(6.83, 23.98) controlPoint2:CGPointMake(9.16, 18.39)];
    [fill1 addLineToPoint:CGPointMake(14.16, 13.39)];
    [fill1 addCurveToPoint:CGPointMake(29.98, 6.83) controlPoint1:CGPointMake(18.39, 9.16) controlPoint2:CGPointMake(24, 6.83)];
    [fill1 addCurveToPoint:CGPointMake(45.66, 13.25) controlPoint1:CGPointMake(35.89, 6.83) controlPoint2:CGPointMake(41.45, 9.11)];
    [fill1 addCurveToPoint:CGPointMake(53.54, 17.02) controlPoint1:CGPointMake(46.44, 14.21) controlPoint2:CGPointMake(49.13, 17.02)];
    [fill1 addCurveToPoint:CGPointMake(61.49, 13.19) controlPoint1:CGPointMake(58.15, 17.02) controlPoint2:CGPointMake(60.65, 14.31)];
    [fill1 addCurveToPoint:CGPointMake(77.11, 6.83) controlPoint1:CGPointMake(65.69, 9.09) controlPoint2:CGPointMake(71.22, 6.83)];
    [fill1 addCurveToPoint:CGPointMake(92.93, 13.39) controlPoint1:CGPointMake(83.08, 6.83) controlPoint2:CGPointMake(88.7, 9.16)];
    [fill1 addLineToPoint:CGPointMake(93.7, 14.16)];
    [fill1 addCurveToPoint:CGPointMake(100.25, 29.92) controlPoint1:CGPointMake(97.92, 18.39) controlPoint2:CGPointMake(100.25, 23.98)];
    [fill1 addCurveToPoint:CGPointMake(93.7, 45.67) controlPoint1:CGPointMake(100.25, 35.85) controlPoint2:CGPointMake(97.92, 41.45)];
    [fill1 moveToPoint:CGPointMake(98.53, 9.33)];
    [fill1 addLineToPoint:CGPointMake(97.76, 8.55)];
    [fill1 addCurveToPoint:CGPointMake(77.11, 0) controlPoint1:CGPointMake(92.24, 3.04) controlPoint2:CGPointMake(84.91, 0)];
    [fill1 addCurveToPoint:CGPointMake(56.46, 8.55) controlPoint1:CGPointMake(69.31, 0) controlPoint2:CGPointMake(61.97, 3.04)];
    [fill1 addCurveToPoint:CGPointMake(56.01, 9.1) controlPoint1:CGPointMake(56.27, 8.75) controlPoint2:CGPointMake(56.15, 8.87)];
    [fill1 addCurveToPoint:CGPointMake(53.54, 10.19) controlPoint1:CGPointMake(55.93, 9.21) controlPoint2:CGPointMake(55.19, 10.19)];
    [fill1 addCurveToPoint:CGPointMake(50.98, 8.96) controlPoint1:CGPointMake(51.97, 10.19) controlPoint2:CGPointMake(50.98, 8.96)];
    [fill1 addCurveToPoint:CGPointMake(50.63, 8.55) controlPoint1:CGPointMake(50.87, 8.82) controlPoint2:CGPointMake(50.76, 8.68)];
    [fill1 addCurveToPoint:CGPointMake(29.98, 0) controlPoint1:CGPointMake(45.11, 3.04) controlPoint2:CGPointMake(37.78, 0)];
    [fill1 addCurveToPoint:CGPointMake(9.33, 8.55) controlPoint1:CGPointMake(22.18, 0) controlPoint2:CGPointMake(14.84, 3.04)];
    [fill1 addLineToPoint:CGPointMake(8.55, 9.33)];
    [fill1 addCurveToPoint:CGPointMake(0, 29.92) controlPoint1:CGPointMake(3.04, 14.84) controlPoint2:CGPointMake(0, 22.16)];
    [fill1 addCurveToPoint:CGPointMake(8.44, 50.39) controlPoint1:CGPointMake(0, 37.62) controlPoint2:CGPointMake(2.99, 44.89)];
    [fill1 addCurveToPoint:CGPointMake(45.15, 93.7) controlPoint1:CGPointMake(10.75, 53.18) controlPoint2:CGPointMake(40.79, 89.34)];
    [fill1 addCurveToPoint:CGPointMake(53.65, 98) controlPoint1:CGPointMake(47, 95.54) controlPoint2:CGPointMake(49.88, 98)];
    [fill1 addCurveToPoint:CGPointMake(62.16, 93.7) controlPoint1:CGPointMake(57.42, 98) controlPoint2:CGPointMake(60.31, 95.54)];
    [fill1 addCurveToPoint:CGPointMake(98.65, 50.38) controlPoint1:CGPointMake(67.18, 88.68) controlPoint2:CGPointMake(96.34, 53.2)];
    [fill1 addCurveToPoint:CGPointMake(107.09, 29.92) controlPoint1:CGPointMake(104.09, 44.88) controlPoint2:CGPointMake(107.09, 37.62)];
    [fill1 addCurveToPoint:CGPointMake(98.53, 9.33) controlPoint1:CGPointMake(107.09, 22.16) controlPoint2:CGPointMake(104.05, 14.84)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 26, 31);
    fill1.usesEvenOddFillRule = YES;
    [[LTLThemeManager sharedManager].themeColor setFill];
    [fill1 fill];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}


#pragma mark - Canvas Images

//! Page 1

+(UIImage *) imageOfLikeList
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(160, 160), NO, 0);
    [LTLlikeList drawLikeList];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfLikeListWithSize:(CGSize)size resizing:(LTLlikeListResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLlikeList drawLikeListWithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}


#pragma mark - Resizing Behavior

CGRect LTLlikeListResizingBehaviorApply(LTLlikeListResizingBehavior behavior, CGRect rect, CGRect target)
{
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero))
    {
        return rect;
    }
    
    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);
    
    switch (behavior)
    {
        case LTLlikeListResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case LTLlikeListResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case LTLlikeListResizingBehaviorStretch:
            break;
        
        case LTLlikeListResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }
    
    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}


@end
