//
//  LTLlikeList.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/16.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLlikeList : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLlikeListResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLlikeListResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLlikeListResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLlikeListResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLlikeListResizingBehavior;

extern CGRect LTLlikeListResizingBehaviorApply(LTLlikeListResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawLikeList;
+(void) drawLikeListWithFrame:(CGRect)frame resizing:(LTLlikeListResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfLikeList;
+(UIImage *) imageOfLikeListWithSize:(CGSize)size resizing:(LTLlikeListResizingBehavior)resizing;


@end
