//
//  LTLMusicBackground.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/17.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLMusicBackground : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLMusicBackgroundResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLMusicBackgroundResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLMusicBackgroundResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLMusicBackgroundResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLMusicBackgroundResizingBehavior;

extern CGRect LTLMusicBackgroundResizingBehaviorApply(LTLMusicBackgroundResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawMusicBackground;
+(void) drawMusicBackgroundWithFrame:(CGRect)frame resizing:(LTLMusicBackgroundResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfMusicBackground;
+(UIImage *) imageOfMusicBackgroundWithSize:(CGSize)size resizing:(LTLMusicBackgroundResizingBehavior)resizing;


@end
