//
//  LTLPlayControlIcon.m
//  音乐播放器
//
//  Created by 李泰良 on 16/11/26.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;
#import "LTLPlayControlIcon.h"



@implementation LTLPlayControlIcon


#pragma mark - Canvas Drawings

//! Page 1

+(void) drawNextHead1
{
    [LTLPlayControlIcon drawNextHead1WithFrame:CGRectMake(0, 0, 45, 45) resizing:LTLPlayControlIconResizingBehaviorAspectFit];
}

+(void) drawNextHead1WithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLPlayControlIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 45, 45), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 45, resizedFrame.size.height / 45);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! NextHead1
    UIBezierPath *nextHead2 = [UIBezierPath bezierPath];
    [nextHead2 moveToPoint:CGPointMake(2.26, 0.2)];
    [nextHead2 addLineToPoint:CGPointMake(19.11, 9.94)];
    [nextHead2 addCurveToPoint:CGPointMake(19.11, 12.54) controlPoint1:CGPointMake(20.12, 10.52) controlPoint2:CGPointMake(20.12, 11.96)];
    [nextHead2 addLineToPoint:CGPointMake(2.26, 22.28)];
    [nextHead2 addCurveToPoint:CGPointMake(0, 20.97) controlPoint1:CGPointMake(1.26, 22.86) controlPoint2:CGPointMake(0, 22.13)];
    [nextHead2 addLineToPoint:CGPointMake(0, 1.51)];
    [nextHead2 addCurveToPoint:CGPointMake(2.26, 0.2) controlPoint1:CGPointMake(0, 0.35) controlPoint2:CGPointMake(1.26, -0.38)];
    [nextHead2 closePath];
    [nextHead2 moveToPoint:CGPointMake(28.53, 22.6)];
    [nextHead2 addLineToPoint:CGPointMake(25, 22.6)];
    [nextHead2 addCurveToPoint:CGPointMake(23, 20.6) controlPoint1:CGPointMake(23.9, 22.6) controlPoint2:CGPointMake(23, 21.7)];
    [nextHead2 addLineToPoint:CGPointMake(23, 2)];
    [nextHead2 addCurveToPoint:CGPointMake(25, 0) controlPoint1:CGPointMake(23, 0.9) controlPoint2:CGPointMake(23.9, 0)];
    [nextHead2 addLineToPoint:CGPointMake(28.53, 0)];
    [nextHead2 addCurveToPoint:CGPointMake(30.53, 2) controlPoint1:CGPointMake(29.63, 0) controlPoint2:CGPointMake(30.53, 0.9)];
    [nextHead2 addLineToPoint:CGPointMake(30.53, 20.6)];
    [nextHead2 addCurveToPoint:CGPointMake(28.53, 22.6) controlPoint1:CGPointMake(30.53, 21.7) controlPoint2:CGPointMake(29.63, 22.6)];
    [nextHead2 closePath];
    [nextHead2 moveToPoint:CGPointMake(28.53, 22.6)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 8, 11);
    nextHead2.lineJoinStyle = kCGLineJoinRound;
    nextHead2.lineCapStyle = kCGLineCapRound;
    nextHead2.lineWidth = 4;
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [nextHead2 stroke];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}

+(void) drawPlay
{
    [LTLPlayControlIcon drawPlayWithFrame:CGRectMake(0, 0, 75, 75) resizing:LTLPlayControlIconResizingBehaviorAspectFit];
}

+(void) drawPlayWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLPlayControlIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 75, 75), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 75, resizedFrame.size.height / 75);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! play
    UIBezierPath *play2 = [UIBezierPath bezierPath];
    [play2 moveToPoint:CGPointMake(60, 30)];
    [play2 addCurveToPoint:CGPointMake(30, 60) controlPoint1:CGPointMake(60, 46.57) controlPoint2:CGPointMake(46.57, 60)];
    [play2 addCurveToPoint:CGPointMake(0, 30) controlPoint1:CGPointMake(13.43, 60) controlPoint2:CGPointMake(0, 46.57)];
    [play2 addCurveToPoint:CGPointMake(30, 0) controlPoint1:CGPointMake(0, 13.43) controlPoint2:CGPointMake(13.43, 0)];
    [play2 addCurveToPoint:CGPointMake(60, 30) controlPoint1:CGPointMake(46.57, 0) controlPoint2:CGPointMake(60, 13.43)];
    [play2 closePath];
    [play2 moveToPoint:CGPointMake(23.63, 15.96)];
    [play2 addLineToPoint:CGPointMake(45.66, 28.68)];
    [play2 addCurveToPoint:CGPointMake(45.66, 32.09) controlPoint1:CGPointMake(46.97, 29.44) controlPoint2:CGPointMake(46.97, 31.33)];
    [play2 addLineToPoint:CGPointMake(23.63, 44.81)];
    [play2 addCurveToPoint:CGPointMake(20.68, 43.1) controlPoint1:CGPointMake(22.32, 45.57) controlPoint2:CGPointMake(20.68, 44.62)];
    [play2 addLineToPoint:CGPointMake(20.68, 17.66)];
    [play2 addCurveToPoint:CGPointMake(23.63, 15.96) controlPoint1:CGPointMake(20.68, 16.15) controlPoint2:CGPointMake(22.32, 15.2)];
    [play2 closePath];
    [play2 moveToPoint:CGPointMake(23.63, 15.96)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 8, 8);
    play2.lineJoinStyle = kCGLineJoinRound;
    play2.lineCapStyle = kCGLineCapRound;
    play2.lineWidth = 4;
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [play2 stroke];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}

+(void) drawLastOne
{
    [LTLPlayControlIcon drawLastOneWithFrame:CGRectMake(0, 0, 60, 60) resizing:LTLPlayControlIconResizingBehaviorAspectFit];
}

+(void) drawLastOneWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLPlayControlIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 60, 60), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 60, resizedFrame.size.height / 60);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! LastOne
    UIBezierPath *lastOne2 = [UIBezierPath bezierPath];
    [lastOne2 moveToPoint:CGPointMake(52, 26)];
    [lastOne2 addCurveToPoint:CGPointMake(26, 52) controlPoint1:CGPointMake(52, 40.36) controlPoint2:CGPointMake(40.36, 52)];
    [lastOne2 addCurveToPoint:CGPointMake(0, 26) controlPoint1:CGPointMake(11.64, 52) controlPoint2:CGPointMake(0, 40.36)];
    [lastOne2 addCurveToPoint:CGPointMake(26, 0) controlPoint1:CGPointMake(0, 11.64) controlPoint2:CGPointMake(11.64, 0)];
    [lastOne2 addCurveToPoint:CGPointMake(52, 26) controlPoint1:CGPointMake(40.36, 0) controlPoint2:CGPointMake(52, 11.64)];
    [lastOne2 closePath];
    [lastOne2 moveToPoint:CGPointMake(39.74, 37.04)];
    [lastOne2 addLineToPoint:CGPointMake(22.88, 27.3)];
    [lastOne2 addCurveToPoint:CGPointMake(22.88, 24.7) controlPoint1:CGPointMake(21.88, 26.72) controlPoint2:CGPointMake(21.88, 25.28)];
    [lastOne2 addLineToPoint:CGPointMake(39.74, 14.96)];
    [lastOne2 addCurveToPoint:CGPointMake(42, 16.27) controlPoint1:CGPointMake(40.74, 14.38) controlPoint2:CGPointMake(42, 15.11)];
    [lastOne2 addLineToPoint:CGPointMake(42, 35.73)];
    [lastOne2 addCurveToPoint:CGPointMake(39.74, 37.04) controlPoint1:CGPointMake(42, 36.89) controlPoint2:CGPointMake(40.74, 37.62)];
    [lastOne2 closePath];
    [lastOne2 moveToPoint:CGPointMake(13.99, 14.7)];
    [lastOne2 addLineToPoint:CGPointMake(17.52, 14.7)];
    [lastOne2 addCurveToPoint:CGPointMake(19.52, 16.7) controlPoint1:CGPointMake(18.63, 14.7) controlPoint2:CGPointMake(19.52, 15.6)];
    [lastOne2 addLineToPoint:CGPointMake(19.52, 35.3)];
    [lastOne2 addCurveToPoint:CGPointMake(17.52, 37.3) controlPoint1:CGPointMake(19.52, 36.4) controlPoint2:CGPointMake(18.63, 37.3)];
    [lastOne2 addLineToPoint:CGPointMake(13.99, 37.3)];
    [lastOne2 addCurveToPoint:CGPointMake(11.99, 35.3) controlPoint1:CGPointMake(12.89, 37.3) controlPoint2:CGPointMake(11.99, 36.4)];
    [lastOne2 addLineToPoint:CGPointMake(11.99, 16.7)];
    [lastOne2 addCurveToPoint:CGPointMake(13.99, 14.7) controlPoint1:CGPointMake(11.99, 15.6) controlPoint2:CGPointMake(12.89, 14.7)];
    [lastOne2 closePath];
    [lastOne2 moveToPoint:CGPointMake(13.99, 14.7)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 5, 4);
    lastOne2.lineJoinStyle = kCGLineJoinRound;
    lastOne2.lineCapStyle = kCGLineCapRound;
    lastOne2.lineWidth = 4;
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [lastOne2 stroke];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}

+(void) drawLastOne1
{
    [LTLPlayControlIcon drawLastOne1WithFrame:CGRectMake(0, 0, 45, 45) resizing:LTLPlayControlIconResizingBehaviorAspectFit];
}

+(void) drawLastOne1WithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLPlayControlIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 45, 45), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 45, resizedFrame.size.height / 45);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! LastOne1
    UIBezierPath *lastOne2 = [UIBezierPath bezierPath];
    [lastOne2 moveToPoint:CGPointMake(27.74, 22.33)];
    [lastOne2 addLineToPoint:CGPointMake(10.89, 12.6)];
    [lastOne2 addCurveToPoint:CGPointMake(10.89, 9.99) controlPoint1:CGPointMake(9.88, 12.02) controlPoint2:CGPointMake(9.88, 10.57)];
    [lastOne2 addLineToPoint:CGPointMake(27.74, 0.26)];
    [lastOne2 addCurveToPoint:CGPointMake(30, 1.57) controlPoint1:CGPointMake(28.74, -0.32) controlPoint2:CGPointMake(30, 0.41)];
    [lastOne2 addLineToPoint:CGPointMake(30, 21.03)];
    [lastOne2 addCurveToPoint:CGPointMake(27.74, 22.33) controlPoint1:CGPointMake(30, 22.19) controlPoint2:CGPointMake(28.74, 22.91)];
    [lastOne2 closePath];
    [lastOne2 moveToPoint:CGPointMake(2, 0)];
    [lastOne2 addLineToPoint:CGPointMake(5.53, 0)];
    [lastOne2 addCurveToPoint:CGPointMake(7.53, 2) controlPoint1:CGPointMake(6.64, 0) controlPoint2:CGPointMake(7.53, 0.9)];
    [lastOne2 addLineToPoint:CGPointMake(7.53, 20.6)];
    [lastOne2 addCurveToPoint:CGPointMake(5.53, 22.6) controlPoint1:CGPointMake(7.53, 21.7) controlPoint2:CGPointMake(6.64, 22.6)];
    [lastOne2 addLineToPoint:CGPointMake(2, 22.6)];
    [lastOne2 addCurveToPoint:CGPointMake(0, 20.6) controlPoint1:CGPointMake(0.9, 22.6) controlPoint2:CGPointMake(0, 21.7)];
    [lastOne2 addLineToPoint:CGPointMake(0, 2)];
    [lastOne2 addCurveToPoint:CGPointMake(2, 0) controlPoint1:CGPointMake(0, 0.9) controlPoint2:CGPointMake(0.9, 0)];
    [lastOne2 closePath];
    [lastOne2 moveToPoint:CGPointMake(2, 0)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 7.99, 11.7);
    lastOne2.lineJoinStyle = kCGLineJoinRound;
    lastOne2.lineCapStyle = kCGLineCapRound;
    lastOne2.lineWidth = 4;
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [lastOne2 stroke];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}

+(void) drawSuspend
{
    [LTLPlayControlIcon drawSuspendWithFrame:CGRectMake(0, 0, 75, 75) resizing:LTLPlayControlIconResizingBehaviorAspectFit];
}

+(void) drawSuspendWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLPlayControlIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 75, 75), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 75, resizedFrame.size.height / 75);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! Combined Shape
    UIBezierPath *combinedShape = [UIBezierPath bezierPath];
    [combinedShape moveToPoint:CGPointMake(60, 30)];
    [combinedShape addCurveToPoint:CGPointMake(30, 60) controlPoint1:CGPointMake(60, 46.57) controlPoint2:CGPointMake(46.57, 60)];
    [combinedShape addCurveToPoint:CGPointMake(0, 30) controlPoint1:CGPointMake(13.43, 60) controlPoint2:CGPointMake(0, 46.57)];
    [combinedShape addCurveToPoint:CGPointMake(30, 0) controlPoint1:CGPointMake(0, 13.43) controlPoint2:CGPointMake(13.43, 0)];
    [combinedShape addCurveToPoint:CGPointMake(60, 30) controlPoint1:CGPointMake(46.57, 0) controlPoint2:CGPointMake(60, 13.43)];
    [combinedShape closePath];
    [combinedShape moveToPoint:CGPointMake(23.2, 43.69)];
    [combinedShape addLineToPoint:CGPointMake(17.8, 43.69)];
    [combinedShape addCurveToPoint:CGPointMake(16, 41.84) controlPoint1:CGPointMake(16.81, 43.69) controlPoint2:CGPointMake(16, 42.86)];
    [combinedShape addLineToPoint:CGPointMake(16, 17.85)];
    [combinedShape addCurveToPoint:CGPointMake(17.8, 16) controlPoint1:CGPointMake(16, 16.83) controlPoint2:CGPointMake(16.81, 16)];
    [combinedShape addLineToPoint:CGPointMake(23.2, 16)];
    [combinedShape addCurveToPoint:CGPointMake(25, 17.85) controlPoint1:CGPointMake(24.19, 16) controlPoint2:CGPointMake(25, 16.83)];
    [combinedShape addLineToPoint:CGPointMake(25, 41.84)];
    [combinedShape addCurveToPoint:CGPointMake(23.2, 43.69) controlPoint1:CGPointMake(25, 42.86) controlPoint2:CGPointMake(24.19, 43.69)];
    [combinedShape closePath];
    [combinedShape moveToPoint:CGPointMake(42.2, 43.69)];
    [combinedShape addLineToPoint:CGPointMake(36.8, 43.69)];
    [combinedShape addCurveToPoint:CGPointMake(35, 41.85) controlPoint1:CGPointMake(35.81, 43.69) controlPoint2:CGPointMake(35, 42.87)];
    [combinedShape addLineToPoint:CGPointMake(35, 17.85)];
    [combinedShape addCurveToPoint:CGPointMake(36.8, 16) controlPoint1:CGPointMake(35, 16.83) controlPoint2:CGPointMake(35.81, 16)];
    [combinedShape addLineToPoint:CGPointMake(42.2, 16)];
    [combinedShape addCurveToPoint:CGPointMake(44, 17.85) controlPoint1:CGPointMake(43.19, 16) controlPoint2:CGPointMake(44, 16.83)];
    [combinedShape addLineToPoint:CGPointMake(44, 41.85)];
    [combinedShape addCurveToPoint:CGPointMake(42.2, 43.69) controlPoint1:CGPointMake(44, 42.87) controlPoint2:CGPointMake(43.19, 43.69)];
    [combinedShape closePath];
    [combinedShape moveToPoint:CGPointMake(42.2, 43.69)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 8, 8);
    combinedShape.lineJoinStyle = kCGLineJoinRound;
    combinedShape.lineCapStyle = kCGLineCapRound;
    combinedShape.lineWidth = 4;
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [combinedShape stroke];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}

+(void) drawNextHead
{
    [LTLPlayControlIcon drawNextHeadWithFrame:CGRectMake(0, 0, 60, 60) resizing:LTLPlayControlIconResizingBehaviorAspectFit];
}

+(void) drawNextHeadWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    //! General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //! Resize To Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = LTLPlayControlIconResizingBehaviorApply(resizing, CGRectMake(0, 0, 60, 60), frame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGSize resizedScale = CGSizeMake(resizedFrame.size.width / 60, resizedFrame.size.height / 60);
    CGContextScaleCTM(context, resizedScale.width, resizedScale.height);
    
    //! Combined Shape
    UIBezierPath *combinedShape = [UIBezierPath bezierPath];
    [combinedShape moveToPoint:CGPointMake(52, 26)];
    [combinedShape addCurveToPoint:CGPointMake(26, 52) controlPoint1:CGPointMake(52, 40.36) controlPoint2:CGPointMake(40.36, 52)];
    [combinedShape addCurveToPoint:CGPointMake(0, 26) controlPoint1:CGPointMake(11.64, 52) controlPoint2:CGPointMake(0, 40.36)];
    [combinedShape addCurveToPoint:CGPointMake(26, 0) controlPoint1:CGPointMake(0, 11.64) controlPoint2:CGPointMake(11.64, 0)];
    [combinedShape addCurveToPoint:CGPointMake(52, 26) controlPoint1:CGPointMake(40.36, 0) controlPoint2:CGPointMake(52, 11.64)];
    [combinedShape closePath];
    [combinedShape moveToPoint:CGPointMake(40.53, 37.6)];
    [combinedShape addLineToPoint:CGPointMake(37, 37.6)];
    [combinedShape addCurveToPoint:CGPointMake(35, 35.6) controlPoint1:CGPointMake(35.89, 37.6) controlPoint2:CGPointMake(35, 36.7)];
    [combinedShape addLineToPoint:CGPointMake(35, 17)];
    [combinedShape addCurveToPoint:CGPointMake(37, 15) controlPoint1:CGPointMake(35, 15.9) controlPoint2:CGPointMake(35.89, 15)];
    [combinedShape addLineToPoint:CGPointMake(40.53, 15)];
    [combinedShape addCurveToPoint:CGPointMake(42.53, 17) controlPoint1:CGPointMake(41.64, 15) controlPoint2:CGPointMake(42.53, 15.9)];
    [combinedShape addLineToPoint:CGPointMake(42.53, 35.6)];
    [combinedShape addCurveToPoint:CGPointMake(40.53, 37.6) controlPoint1:CGPointMake(42.53, 36.7) controlPoint2:CGPointMake(41.64, 37.6)];
    [combinedShape closePath];
    [combinedShape moveToPoint:CGPointMake(14.26, 15.2)];
    [combinedShape addLineToPoint:CGPointMake(31.11, 24.94)];
    [combinedShape addCurveToPoint:CGPointMake(31.11, 27.54) controlPoint1:CGPointMake(32.12, 25.52) controlPoint2:CGPointMake(32.12, 26.96)];
    [combinedShape addLineToPoint:CGPointMake(14.26, 37.28)];
    [combinedShape addCurveToPoint:CGPointMake(12, 35.97) controlPoint1:CGPointMake(13.26, 37.86) controlPoint2:CGPointMake(12, 37.13)];
    [combinedShape addLineToPoint:CGPointMake(12, 16.51)];
    [combinedShape addCurveToPoint:CGPointMake(14.26, 15.2) controlPoint1:CGPointMake(12, 15.35) controlPoint2:CGPointMake(13.26, 14.62)];
    [combinedShape closePath];
    [combinedShape moveToPoint:CGPointMake(14.26, 15.2)];
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 5, 4);
    combinedShape.lineJoinStyle = kCGLineJoinRound;
    combinedShape.lineCapStyle = kCGLineCapRound;
    combinedShape.lineWidth = 4;
    [[LTLThemeManager sharedManager].themeColor setStroke];
    [combinedShape stroke];
    CGContextRestoreGState(context);
    
    CGContextRestoreGState(context);
}


#pragma mark - Canvas Images

//! Page 1

+(UIImage *) imageOfNextHead1
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(45, 45), NO, 0);
    [LTLPlayControlIcon drawNextHead1];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfNextHead1WithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLPlayControlIcon drawNextHead1WithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfPlay
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(75, 75), NO, 0);
    [LTLPlayControlIcon drawPlay];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfPlayWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLPlayControlIcon drawPlayWithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfLastOne
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(60, 60), NO, 0);
    [LTLPlayControlIcon drawLastOne];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfLastOneWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLPlayControlIcon drawLastOneWithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfLastOne1
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(45, 45), NO, 0);
    [LTLPlayControlIcon drawLastOne1];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfLastOne1WithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLPlayControlIcon drawLastOne1WithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfSuspend
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(75, 75), NO, 0);
    [LTLPlayControlIcon drawSuspend];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfSuspendWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLPlayControlIcon drawSuspendWithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfNextHead
{
    static UIImage * image = nil;
    if (image != nil)
        return image;
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(60, 60), NO, 0);
    [LTLPlayControlIcon drawNextHead];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+(UIImage *) imageOfNextHeadWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing
{
    UIImage *image = nil;
    
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    [LTLPlayControlIcon drawNextHeadWithFrame:CGRectMake(0, 0, size.width, size.height) resizing:resizing];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}


#pragma mark - Resizing Behavior

CGRect LTLPlayControlIconResizingBehaviorApply(LTLPlayControlIconResizingBehavior behavior, CGRect rect, CGRect target)
{
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero))
    {
        return rect;
    }
    
    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);
    
    switch (behavior)
    {
        case LTLPlayControlIconResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case LTLPlayControlIconResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case LTLPlayControlIconResizingBehaviorStretch:
            break;
        
        case LTLPlayControlIconResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }
    
    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}


@end
