//
//  LTLPlayControlIcon.h
//  音乐播放器
//
//  Created by 李泰良 on 16/11/26.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLPlayControlIcon : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLPlayControlIconResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLPlayControlIconResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLPlayControlIconResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLPlayControlIconResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLPlayControlIconResizingBehavior;

extern CGRect LTLPlayControlIconResizingBehaviorApply(LTLPlayControlIconResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawNextHead1;
+(void) drawNextHead1WithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(void) drawPlay;
+(void) drawPlayWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(void) drawLastOne;
+(void) drawLastOneWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(void) drawLastOne1;
+(void) drawLastOne1WithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(void) drawSuspend;
+(void) drawSuspendWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(void) drawNextHead;
+(void) drawNextHeadWithFrame:(CGRect)frame resizing:(LTLPlayControlIconResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfNextHead1;
+(UIImage *) imageOfNextHead1WithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(UIImage *) imageOfPlay;
+(UIImage *) imageOfPlayWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(UIImage *) imageOfLastOne;
+(UIImage *) imageOfLastOneWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(UIImage *) imageOfLastOne1;
+(UIImage *) imageOfLastOne1WithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(UIImage *) imageOfSuspend;
+(UIImage *) imageOfSuspendWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing;
+(UIImage *) imageOfNextHead;
+(UIImage *) imageOfNextHeadWithSize:(CGSize)size resizing:(LTLPlayControlIconResizingBehavior)resizing;


@end
