//
//  LTLSetMore.h
//  音乐播放器
//
//  Created by 李泰良 on 16/11/26.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLSetMore : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLSetMoreResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLSetMoreResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLSetMoreResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLSetMoreResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLSetMoreResizingBehavior;

extern CGRect LTLSetMoreResizingBehaviorApply(LTLSetMoreResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawArtboard;
+(void) drawArtboardWithFrame:(CGRect)frame resizing:(LTLSetMoreResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfArtboard;
+(UIImage *) imageOfArtboardWithSize:(CGSize)size resizing:(LTLSetMoreResizingBehavior)resizing;


@end
