//
//  LTLskin.h
//  音乐播放器
//
//  Created by 李泰良 on 16/12/16.
//  Copyright © 2016 LTL. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface LTLskin : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger
{
    LTLskinResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    LTLskinResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    LTLskinResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    LTLskinResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
    
} LTLskinResizingBehavior;

extern CGRect LTLskinResizingBehaviorApply(LTLskinResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+(void) drawSkin;
+(void) drawSkinWithFrame:(CGRect)frame resizing:(LTLskinResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+(UIImage *) imageOfSkin;
+(UIImage *) imageOfSkinWithSize:(CGSize)size resizing:(LTLskinResizingBehavior)resizing;


@end
